name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # === জাভা ভার্সন ১৭ সেট করা হয়েছে ===
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project and prepare files
        run: |
          cordova create temp_cordova com.shrutipaath.app "ShrutiPaath"
          rm -rf temp_cordova/www
          mkdir temp_cordova/www
          cp -r css js index.html temp_cordova/www/
          cp config.xml temp_cordova/

      - name: Add platforms and plugins
        working-directory: ./temp_cordova
        run: |
          cordova platform add android
          cordova plugin add cordova-plugin-file
          cordova plugin add cordova-plugin-file-transfer
          cordova plugin add cordova-plugin-media
          cordova telemetry off

      - name: Build Android App
        working-directory: ./temp_cordova
        run: cordova build android --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shrutipaath-hybrid-apk
          path: temp_cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
